[build]
  command = "npm run build"
  # Setting publish to .next to override UI setting
  # The plugin will handle the actual deployment
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"

